### ISSUE TITLE
Majority of autosplitter functions aren't working for itch copies of ASH

### ISSUE THREAD

**Issue by caeyo** [ldmnt/ash-autosplitter#10]
I tagged Hamb and Ero in the ASH server to report this but unfortunately I think it was missed, so I'm opening this issue just to have it properly tracked.

The version of the autosplitter hosted here does not seem to be compatible with itch.io copies of ASH running the latest update (1.8.14). The timer does not automatically start on a new game (but does reset), and the only splits that worked from my testing were Visitor Center Feather 1 and 2, and College Kid Feather 1, 2, 3 and 4.

I have been using the attached file instead of the one hosted here for a while now and all the autosplitter functions work with this on my copy, however from interactions in the server I'm not certain that it will work for other itch copies, so I'm not sure what's going on with that. 

[AShortHike.txt](https://github.com/ldmnt/ash-autosplitter/files/7545390/AShortHike.txt)

Let me know if you need me to do any testing; I'm comfortable chilling with this version of the ASL script so I'm not personally fussed about it getting fixed but I believe other runners with itch copies might.

**Comment by ero-qt** [comment]
First draft [here](https://gist.github.com/just-ero/7d9838ba6ec9c97e0a1fb444b66297f2/604455d657e63bb09880cc25dc574ff5f5175a89). Finds `GlobalData` and its parent `Singleton<T>`. Pointers will be built from here (another day).

**Comment by ero-qt** [comment]
Second draft [here](https://gist.github.com/just-ero/7d9838ba6ec9c97e0a1fb444b66297f2/8fe99806179088986504350faace191ba23b53fe). Downloads an XML with some mono offset information from [here](https://github.com/just-ero/file-hosting/blob/master/mono/mono_v2_x86.xml) to use later in the script.

Then finds `GlobalData` and its parent `Singleton<T>`, as well as `GameServiceLocator` and its parent `AbstractServiceLocator<T>` (whose parent is also `Singleton<T>`). `AbstractServiceLocator<T>` has a `Dictionary<System.Type, ServiceMonoBehaviour>` which hosts `LevelController` at its first entry's `Value` (`LevelController` inherits from `ServiceMonoBehaviour`).

With that, we have both `GlobalData` and `LevelController` and can do anything we want. Timer-specific logic must still be added.

**Comment by ero-qt** [comment]
Final draft [here](https://gist.github.com/just-ero/7d9838ba6ec9c97e0a1fb444b66297f2). Should work perfectly fine on everything now.

This script assumes an existing [`mono_v2_x86.xml`](https://github.com/just-ero/AutoSplitHelp/blob/master/mono/mono_v2_x86.xml) file in `%LiveSplit%\Components`. This is handled by the [`LiveSplit.AutoSplitters.xml`](https://github.com/LiveSplit/LiveSplit.AutoSplitters/blob/master/LiveSplit.AutoSplitters.xml)!
